### ISSUE TITLE
UmbracoADAuthExtensions - Redirect Uri

### ISSUE THREAD

**Issue by justin-ruffin** [umbraco/UmbracoIdentityExtensions#12]
The RedirectUri param is not being set for the OpenIdConnectAuthenticationOptions.

Please find image of corrected source code with the missing line highlighted.

Thanks,
Justin

![image](https://cloud.githubusercontent.com/assets/24457439/21013593/93905c70-bd0f-11e6-90af-8de67fc5528c.png)

**Comment by nul800sebastiaan** [comment]
Hi @justin-ruffin - this looks like a very old issue, apologies for the extremely late reply 🙈

It looks like the param is being set just fine? I am not sure if the issue has been fixed since you reported it.
https://github.com/umbraco/UmbracoIdentityExtensions/blob/master/src/App_Start/UmbracoADAuthExtensions.cs#L64

If you can still reproduce the problem then make sure to describe the issue in as much detail as possible.
