### ISSUE TITLE
Active Directory + autologin

### ISSUE THREAD

**Issue by 3ijtKwijt** [umbraco/UmbracoIdentityExtensions#21]
Works with normal Active Directory => autologin?

**Comment by Shazwazza** [comment]
If you 'normal' AD supports OAuth (OpenIDConnect), then yes, otherwise no. This extension library is mostly for enabling OAuth providers and token authentication.

If you are looking for normal AD, look here: https://our.umbraco.org/Documentation/Reference/Security/#authenticating-with-active-directory-credentials
